@url_dev = http://localhost:8080
@version = v1/api
@model = shop

### signUp
POST {{url_dev}}/{{version}}/{{model}}/signUp
Content-Type: application/json
x-api-key: fca7bf7e8c0aee01de3ec36aa32b820af6f28d556d162a99ac523ce950ecd66305bffada83f997b5aa5d463a5a4a633cc75dfcea0b81e3099060edd73314be57

{
    "name": "Shopify",
    "email": "shopify@gmail.com",
    "password": "mn123456"
}

### login
POST {{url_dev}}/{{version}}/{{model}}/login
Content-Type: application/json
x-api-key: fca7bf7e8c0aee01de3ec36aa32b820af6f28d556d162a99ac523ce950ecd66305bffada83f997b5aa5d463a5a4a633cc75dfcea0b81e3099060edd73314be57

{
    "email": "shopify@gmail.com",
    "password": "mn123456"
}

### logout
POST {{url_dev}}/{{version}}/{{model}}/logout
Content-Type: application/json
x-api-key: fca7bf7e8c0aee01de3ec36aa32b820af6f28d556d162a99ac523ce950ecd66305bffada83f997b5aa5d463a5a4a633cc75dfcea0b81e3099060edd73314be57
x-client-id: 67d8e64a6a7f66f85b6f845c
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2Q4ZTY0YTZhN2Y2NmY4NWI2Zjg0NWMiLCJlbWFpbCI6InNob3BpZnlAZ21haWwuY29tIiwiaWF0IjoxNzQyMjY5MzAzLCJleHAiOjE3NDI0NDIxMDN9.CwTRNr9Z780BsRTF5qpJ-NKV2h0HeEf2GhgYOA9_h7Y